### ISSUE TITLE
Which format is the right one for "connect.sid"?

### ISSUE THREAD

**Issue by m-mattia-m** [maetthu/republik-feeder#3]
Does the "connect.sid" have to be decoded or encoded? Because currently no articles are shown to me with both possibilities, which is probably due to the fact that no new articles have appeared in the meantime.

**Comment by maetthu** [comment]
Just 1:1 as it's stored in the browser, not urldecoded - `REPUBLIK_FEEDER_COOKIE="s%3Asomething"` in my case.

![Screenshot_20230402_110829](https://user-images.githubusercontent.com/1193955/229343547-31535c86-cd14-4d6b-933e-def280679b51.png)

Although if it didn't work either way, maybe the one you tried expired? Mine stopped working when I changed my email address and had to extract the new one again.

**Comment by m-mattia-m** [comment]
Ok thanks. I have now re-registered and taken result from the value, however, still no article is displayed to me. Which items should all be spent? Only those that were added after the API was deployed or also those from last week?

**Comment by maetthu** [comment]
It just returns the 20 most recent articles returned from the Republik API, it's not dependent on the startup time or when the last article was published.  

e.g. started with 

```
$ REPUBLIK_FEEDER_COOKIE="s%3Asomething" ./republik-feeder :8080
``` 

the URL http://localhost:8080/articles should return a list like

```
$ curl http://localhost:8080/articles
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Republik - RSS Feed</title>
    <link>https://www.republik.ch</link>
    <description>Republik - RSS Feed</description>
    <managingEditor>kontakt@republik.ch (Republik)</managingEditor>
    <pubDate>Sun, 02 Apr 2023 11:35:13 +0200</pubDate>
    <item>
      <title>[Wochenend-Newsletter] Schweizer Klimaseniorinnen in Strassburg und der Wochenkommentar</title>
      <link>https://www.republik.ch/URL-TO-ARTICLE</link>
      <description></description>
      <guid>...</guid>
      <pubDate>Sat, 01 Apr 2023 03:00:00 +0000</pubDate>
    </item>
    <item>
      <title>Frau Stern reist nach Strassburg</title>
      <link>https://www.republik.ch/URL-TO-ARTICLE</link>
      <description>Den eigenen Staat verklagen und siebzehn Richtern Rede und Antwort stehen: Das machen die Schweizer Klima­seniorinnen vor dem Europäischen Gerichtshof für Menschen­rechte. Unter den Augen der Welt­öffentlichkeit.</description>
      <guid>...</guid>
      <pubDate>Sat, 01 Apr 2023 02:50:00 +0000</pubDate>
    </item>
    [...]
  </channel>
</rss>
```

**Comment by m-mattia-m** [comment]
Interesting, with me only the following is displayed? 

```xml
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
    <channel>
        <title>Republik - RSS Feed</title>
        <link>https://www.republik.ch</link>
        <description>Republik - RSS Feed</description>
        <managingEditor>kontakt@republik.ch (Republik)</managingEditor>
        <pubDate>Sun, 02 Apr 2023 09:35:44 +0000</pubDate>
    </channel>
</rss>
```

The problem was that I didn't have a paid profile yet. Now it works.
