### ISSUE TITLE
Pass article limit as CLI argument

### ISSUE THREAD

**Issue by mar0th** [maetthu/republik-feeder#4]
The article limit is currently hard-coded to 20 articles. Is there a reason for this limit?

It would be great if we could pass this limit as a CLI argument to allow longer feeds.

**Comment by maetthu** [comment]
No reason, just thought it's a reasonable amount since those are getting scraped regularly anyways. I'll add an env var to configure it.

**Comment by mar0th** [comment]
Thanks, the env var is even better.

**Comment by maetthu** [comment]
Just released 1.3.0 which allows overriding the article limit.
